name: Run auto-merge script

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the Python script on'
        required: true
        default: 'main'

jobs:
  auto-merge-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GH }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_TEST }}
        run: |
          python test.py --branch ${{ github.event.inputs.branch }}
